node-base: &node-base
  steps:
    - checkout
    - restore_cache:
        keys:
          - v1-npm-deps-{{ checksum "package-lock.json" }}
          - v1-npm-deps-
    - run: npm install
    - run: npm test
    - save_cache:
        key: v1-npm-deps-{{ checksum "package-lock.json" }}
        paths:
          - node_modules

version: 2.1
jobs:
  test-v10:
    docker:
      - image: circleci/node:10
    <<: *node-base
  test-v12:
    docker:
      - image: circleci/node:11
    <<: *node-base
  test-v14:
    docker:
      - image: circleci/node:12
    <<: *node-base
workflows:
  version: 2
  build:
    jobs:
      - test-v10
      - test-v12
      - test-v13
