version: 2.1
orbs:
  node: circleci/node@5.2
jobs:
  test-v12:
    docker:
      - image: cimg/base:stable
    steps:
      - node/install:
          node-version: "12.22"
      - run: npm install
workflows:
  build:
    jobs:
      - test-v12
