version: 2.1
orbs:
  node: circleci/node@5.2
jobs:
  test-v8:
    docker:
      - image: cimg/base:node8
    steps:
      - node/install-packages:
          with-cache: true 
          pkg-manager: npm 
          include-branch-in-cache-key: true 
          check-cache: never 
          cache-only-lockfile: true 
  test-v10:
    docker:
      - image: cimg/base:node10
    steps:
      - node/install-packages:
          with-cache: true 
          pkg-manager: npm 
          include-branch-in-cache-key: true 
          check-cache: never 
          cache-only-lockfile: true 
  test-v12:
    docker:
      - image: cimg/base:node12
    steps:
      - node/install-packages:
          with-cache: true 
          pkg-manager: npm 
          include-branch-in-cache-key: true 
          check-cache: never 
          cache-only-lockfile: true 
  test-v14:
    docker:
      - image: cimg/base:node14
    steps:
      - node/install-packages:
          with-cache: true 
          pkg-manager: npm 
          include-branch-in-cache-key: true 
          check-cache: never 
          cache-only-lockfile: true 
  test-v16:
    docker:
      - image: cimg/base:node16
    steps:
      - node/install-packages:
          with-cache: true 
          pkg-manager: npm 
          include-branch-in-cache-key: true 
          check-cache: never 
          cache-only-lockfile: true
  test-v18:
    docker:
      - image: cimg/base:node18
    steps:
      - node/install-packages:
          with-cache: true 
          pkg-manager: npm 
          include-branch-in-cache-key: true 
          check-cache: never 
          cache-only-lockfile: true
  test-v20:
    docker:
      - image: cimg/base:node20
    steps:
      - node/install-packages:
          with-cache: true 
          pkg-manager: npm 
          include-branch-in-cache-key: true 
          check-cache: never 
          cache-only-lockfile: true    
workflows:
  build:
    jobs:
      - test-v8
      - test-v10
      - test-v12
      - test-v14
      - test-v16
      - test-v18
      - test-v20
