version: 2.1
orbs:
  node: circleci/node@5.2
workflows:
    build:
      jobs:
        - node/test:
            pkg-manager: npm 
            resource_class: large 
            test-results-for: other 
            run-command: start 
            version: '12.22' 
